create database capgemini_brennoirvine;

\c capgemini_brennoirvine

CREATE TABLE public.t_sequence (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	is_valid bool NOT NULL,
	"sequence" text NOT NULL
);